name: build
on:
  push:
    tags:
      - 'v*.*.*'  # Matches version tags like v1.0.0, v2.1.0, etc.
  workflow_dispatch:

jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Zip Folder
        run: |
          cd ../
          rm -rf <repository_name>.zip
          zip -r <repository_name>.zip <repository_name> -x ".git/*" ".github/*"

      - name: Upload Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-zip
          path: ../<repository_name>.zip

      - name: Create Draft Release
        id: create_release
        run: |
          gh release create "${{ github.ref }}" ../<repository_name>.zip --title "Build" --notes "Latest Release." --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        run: |
          gh release upload "${{ github.ref }}" ../<repository_name>.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
