name: cs2-sharptimer-webpanel

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_NAME: "cs2-sharptimer-webpanel"

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: cs2-sharptimer-webpanel
      run: |
        zip -r "${{ env.PROJECT_NAME }}.zip" . -x "*.git*" "*.github*"

    - name: Create Release
      id: create_release
      run: |
        TAG_NAME="0.2.0"
        RELEASE_NAME="${{ env.PROJECT_NAME }} Release v${{ env.BUILD_NUMBER }}"
        DESCRIPTION="Release of ${{ env.PROJECT_NAME }}."

        RESPONSE=$(curl -s -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"$RELEASE_NAME\", \"body\": \"$DESCRIPTION\"}")

        UPLOAD_URL=$(echo "$RESPONSE" | jq -r '.upload_url' | sed "s/{?name,label}//")

        curl -s -X POST \
          -H "Content-Type: application/zip" \
          --data-binary @"${{ env.PROJECT_NAME }}.zip" \
          "$UPLOAD_URL?name=${{ env.PROJECT_NAME }}.zip"

    - name: Clean up
      run: rm "${{ env.PROJECT_NAME }}.zip"
