name: Build and Zip Project

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip the project
        run: |
          zip -r cs2-sharptimer-webpanel.zip .

      - name: Upload the zip file
        uses: actions/upload-artifact@v4
        with:
          name: cs2-sharptimer-webpanel
          path: cs2-sharptimer-webpanel.zip
