name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: cs2-sharptimer-webpanel

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Zip entire project
      run: zip -r "${{ env.PROJECT_NAME }}.zip" . -x "*.git*"

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}.zip"
        name: "Release ${{ steps.get_version.outputs.VERSION }}"
        tag: "${{ steps.get_version.outputs.VERSION }}"
        body: |
          Release ${{ steps.get_version.outputs.VERSION }} of ${{ env.PROJECT_NAME }}
