name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  OUTPUT_PATH: "./cs2-sharptimer-webpanel"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Zip
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: '${{ env.PROJECT_NAME }}.zip'
    - name: cs2-sharptimer-webpanel
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "${{ env.PROJECT_NAME }}.zip,${{ env.PROJECT_NAME }}.zip"
        name: "Build ${{ env.BUILD_NUMBER }}"
        tag: "build-${{ env.BUILD_NUMBER }}"
        body: |

